// PRIMEPIP FX COMMAND CENTER — PSYCHOLOGY CORE 2090
// Tailored Trading Scenarios for all 17 Psychological Categories
import { TradingScenario } from './scenarioTypes';

export const SCENARIOS_DATABASE: Record<string, TradingScenario> = {
  // =========================================================================
  // FEAR PILOT — 5 DISTINCT SESSIONS
  // =========================================================================
  'fear_session_1': {
    id: 'fear_session_1',
    categoryId: 'FEAR',
    title: 'Capital Detachment & Risk Acceptance',
    subtitle: 'Simulated Floating Loss Pressure vs Predefined Plan',
    symbol: 'EUR/USD',
    timeframe: 'M15',
    tradeDirection: 'LONG',
    entryPrice: 1.0850,
    stopLossPrice: 1.0825, // 25 pips = 1R ($100)
    takeProfitPrice: 1.0925, // 75 pips = 3R ($300)
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: [
      'Stop-loss level at 1.0825 (M15 Higher Low structure) cleanly broken by candle close',
      'Fundamental shift announced in major central bank statement',
    ],
    learningObjective: 'Learn to separate normal floating drawdown from trade invalidation and prevent fear-driven premature exits.',
    pressureCandleIndex: 5,
    pressureEventTitle: 'COUNTER-PULLBACK SCARE (−0.6R FLOATING LOSS)',
    pressureEventDescription: 'Price pulls back sharply towards 1.0835 (-0.6R / -$60). The market structure remains intact above 1.0825, but red P&L activates an urgent impulse to escape.',
    floatingRAtPressure: -0.6,
    candles: [
      { index: 0, time: '10:00', open: 1.0840, high: 1.0848, low: 1.0838, close: 1.0846, isUp: true, annotation: 'Pre-Setup' },
      { index: 1, time: '10:15', open: 1.0846, high: 1.0855, low: 1.0844, close: 1.0852, isUp: true, annotation: 'Breakout' },
      { index: 2, time: '10:30', open: 1.0850, high: 1.0858, low: 1.0849, close: 1.0854, isUp: true, annotation: 'ENTRY @ 1.0850' },
      { index: 3, time: '10:45', open: 1.0854, high: 1.0862, low: 1.0850, close: 1.0860, isUp: true, annotation: '+0.4R Float' },
      { index: 4, time: '11:00', open: 1.0860, high: 1.0861, low: 1.0842, close: 1.0844, isUp: false, annotation: 'Bearish Wick' },
      { index: 5, time: '11:15', open: 1.0844, high: 1.0845, low: 1.0835, close: 1.0837, isUp: false, annotation: 'PRESSURE POINT (-0.6R)' },
      { index: 6, time: '11:30', open: 1.0837, high: 1.0848, low: 1.0836, close: 1.0847, isUp: true, annotation: 'Support Hold' },
      { index: 7, time: '11:45', open: 1.0847, high: 1.0865, low: 1.0845, close: 1.0862, isUp: true, annotation: 'Recovery' },
      { index: 8, time: '12:00', open: 1.0862, high: 1.0880, low: 1.0860, close: 1.0878, isUp: true, annotation: 'Expansion +1.1R' },
    ],
    options: [
      {
        id: 'opt-review-plan',
        label: 'A. Review Predefined Invalidation Criteria & Hold Position',
        actionText: 'Check structure level (1.0825). Since invalidation is not breached, maintain original stop and let probability play out.',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Plan-Adherent Execution',
        detailedFeedback: {
          processVerdict: 'EXCELLENT DISCIPLINE. You prioritized plan criteria over temporary emotional discomfort.',
          behavioralMechanism: 'Amateur traders treat red P&L as a personal failure; institutional traders view it as normal price discovery noise.',
          probabilisticReality: 'In a 60% win-rate system with 2:1 reward-to-risk, 40% of trades will lose. Fluctuation between entry and stop is not failure—it is required.',
          practicalTakeaway: 'The dollar risk ($100) was emotionally spent the second you placed the order. If invalidation has not occurred, your hands stay off the mouse.',
        },
        reflectionFollowUp: 'Did your body experience a spike of adrenaline when viewing the red candle? How did pausing help you stay grounded?',
      },
      {
        id: 'opt-panic-exit',
        label: 'B. Close Position Immediately to Stop the Pain (−$60)',
        actionText: 'Click "Close Position" to prevent this from turning into a full -$100 loss.',
        decisionCategory: 'IMPULSIVE_EXIT',
        isPlanAligned: false,
        shortDescription: 'Fear-Driven Premature Cut',
        detailedFeedback: {
          processVerdict: 'PROCESS VIOLATION. You exited because of emotional dread, not market invalidation.',
          behavioralMechanism: 'Your amygdala treated the -$60 floating loss as an existential threat and bypassed your prefrontal cortex.',
          probabilisticReality: 'Closing trades prematurely creates an asymmetric flaw: you take full losses on sudden spikes, but take partial losses or tiny gains on winners. Mathematically ruinous over 100 trades.',
          practicalTakeaway: 'Notice that the stop at 1.0825 was never hit. The market frequently retests support before continuing.',
        },
        reflectionFollowUp: 'What specific fear drove you to exit? Was it fear of being wrong, or fear of losing money?',
      },
      {
        id: 'opt-double-down',
        label: 'C. Double Position Size to Lower Average Entry Price',
        actionText: 'Buy another lot at 1.0837 so that any tiny bounce puts you back into green profit quickly.',
        decisionCategory: 'RISK_ESCALATION',
        isPlanAligned: false,
        shortDescription: 'Destructive Martingale Escalation',
        detailedFeedback: {
          processVerdict: 'HIGH RISK SEVERE HAZARD. Adding risk to an unconfirmed pullback violates all professional risk management.',
          behavioralMechanism: 'Dopamine desperation and panic-bargaining. You attempt to force the market to erase your discomfort.',
          probabilisticReality: 'If price continues to your stop at 1.0825, your loss is now 2.5R ($250) instead of the planned 1.0R ($100). Three such trades can trigger account blowout.',
          practicalTakeaway: 'Never add to a losing intraday position unless scaling in was explicitly calculated into your initial trade plan.',
        },
        reflectionFollowUp: 'Why did the urge to "make back the loss immediately" arise? How does that contradict long-term trading longevity?',
      },
    ],
  },

  'fear_session_2': {
    id: 'fear_session_2',
    categoryId: 'FEAR',
    title: '4-7-8 Parasympathetic Vagus Reset',
    subtitle: 'High-Vol Wick Reaction & Physiological Regulation',
    symbol: 'GBP/USD',
    timeframe: 'M5',
    tradeDirection: 'SHORT',
    entryPrice: 1.2720,
    stopLossPrice: 1.2745, // 25 pips
    takeProfitPrice: 1.2645, // 75 pips
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: ['5-minute candle body close above resistance 1.2745'],
    learningObjective: 'Deactivate sympathetic arousal (elevated pulse, shallow breathing) before taking any terminal action.',
    pressureCandleIndex: 4,
    pressureEventTitle: 'AGGRESSIVE BULLISH SPIKE (+18 PIPS AGAINST YOU)',
    pressureEventDescription: 'A sudden liquidity sweep spikes price up to 1.2738, just 7 pips from your stop loss. Your chest tightens and your fingers hover over the close button.',
    floatingRAtPressure: -0.75,
    candles: [
      { index: 0, time: '14:00', open: 1.2728, high: 1.2732, low: 1.2718, close: 1.2722, isUp: false },
      { index: 1, time: '14:05', open: 1.2722, high: 1.2724, low: 1.2715, close: 1.2719, isUp: false, annotation: 'SHORT ENTRY 1.2720' },
      { index: 2, time: '14:10', open: 1.2719, high: 1.2721, low: 1.2708, close: 1.2710, isUp: false, annotation: '+0.4R' },
      { index: 3, time: '14:15', open: 1.2710, high: 1.2725, low: 1.2709, close: 1.2724, isUp: true, annotation: 'Sharp Turn' },
      { index: 4, time: '14:20', open: 1.2724, high: 1.2738, low: 1.2722, close: 1.2736, isUp: true, annotation: 'SPIKE (-0.75R)' },
      { index: 5, time: '14:25', open: 1.2736, high: 1.2737, low: 1.2715, close: 1.2718, isUp: false, annotation: 'Rejection Wick' },
      { index: 6, time: '14:30', open: 1.2718, high: 1.2720, low: 1.2695, close: 1.2698, isUp: false, annotation: 'Breakdown +0.9R' },
    ],
    options: [
      {
        id: 'opt-breathe-pause',
        label: 'A. Remove Hands from Mouse, Complete 4 Paced Breaths, Observe Close',
        actionText: 'Do not click anything. Wait for the 5-minute candle to close to verify if it is an actual breakout or merely a liquidity probe.',
        decisionCategory: 'PAUSE_AND_REGULATE',
        isPlanAligned: true,
        shortDescription: 'Regulated Pause & Validation',
        detailedFeedback: {
          processVerdict: 'MASTER-LEVEL PHYSIOLOGICAL CONTROL. You broke the impulse loop by inserting a physiological pause.',
          behavioralMechanism: 'Paced breathing activates the vagus nerve, reducing heart rate and returning oxygenated blood to the executive cortex.',
          probabilisticReality: 'Institutional algorithms routinely sweep retail liquidity above highs. Panicking at the exact tip of the wick sells at the worst possible price.',
          practicalTakeaway: 'The candle rejected immediately and collapsed down into target. Process protected your trade.',
        },
        reflectionFollowUp: 'How did taking 4 deep breaths physically change the sensation in your chest or hands?',
      },
      {
        id: 'opt-panic-close-wick',
        label: 'B. Market-Close Instantly to Save the Last $25',
        actionText: 'Frantically click close at 1.2738 before it hits the full $100 stop loss.',
        decisionCategory: 'IMPULSIVE_EXIT',
        isPlanAligned: false,
        shortDescription: 'Wick-Tip Panic Liquidation',
        detailedFeedback: {
          processVerdict: 'CLASSIC LIQUIDITY SACRIFICE. You surrendered your position at the exact high of the sweep.',
          behavioralMechanism: 'Action bias: the false belief that doing something immediately is safer than adhering to an existing plan.',
          probabilisticReality: 'By exiting mid-candle, you paid maximum spread and gave away a setup whose technical thesis was still 100% intact.',
          practicalTakeaway: 'If your stop loss is positioned technically outside market structure, trust the stop to do its job. Do not micromanage mid-candle.',
        },
        reflectionFollowUp: 'What thought made waiting for the candle close feel unbearable?',
      },
    ],
  },

  'fear_session_3': {
    id: 'fear_session_3',
    categoryId: 'FEAR',
    title: 'Loss Aversion and Uncertainty Simulation',
    subtitle: 'Enduring Prolonged Consolidation & Market Noise',
    symbol: 'XAU/USD',
    timeframe: 'M15',
    tradeDirection: 'LONG',
    entryPrice: 2350.0,
    stopLossPrice: 2342.0, // $8 = 1R ($100)
    takeProfitPrice: 2366.0, // $16 = 2R ($200)
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: ['M15 close below 2342.0 support base'],
    learningObjective: 'Recognize that market chop is inherently uncertain, and avoid interpreting random volatility as guaranteed failure.',
    pressureCandleIndex: 4,
    pressureEventTitle: 'SIDEWAYS CHOP & CHATTER (45 MINUTES OF UNCERTAINTY)',
    pressureEventDescription: 'Gold prints small choppy wicks oscillating between -0.3R and +0.2R for 4 consecutive candles. Boredom and fear combine into an urge to abandon the trade.',
    floatingRAtPressure: -0.2,
    candles: [
      { index: 0, time: '13:00', open: 2348.0, high: 2351.0, low: 2347.5, close: 2350.2, isUp: true, annotation: 'LONG ENTRY 2350' },
      { index: 1, time: '13:15', open: 2350.2, high: 2352.5, low: 2349.0, close: 2350.8, isUp: true },
      { index: 2, time: '13:30', open: 2350.8, high: 2351.2, low: 2347.8, close: 2348.5, isUp: false, annotation: 'Dull Pullback' },
      { index: 3, time: '13:45', open: 2348.5, high: 2350.4, low: 2348.0, close: 2349.2, isUp: true },
      { index: 4, time: '14:00', open: 2349.2, high: 2350.0, low: 2348.1, close: 2348.4, isUp: false, annotation: 'PRESSURE POINT (CHOP)' },
      { index: 5, time: '14:15', open: 2348.4, high: 2356.0, low: 2348.0, close: 2355.2, isUp: true, annotation: 'Expansion +0.65R' },
      { index: 6, time: '14:30', open: 2355.2, high: 2366.5, low: 2354.8, close: 2366.0, isUp: true, annotation: 'TARGET HIT (+2.0R)' },
    ],
    options: [
      {
        id: 'opt-accept-uncertainty',
        label: 'A. Accept Time Randomness & Let the Setup Mature',
        actionText: 'Acknowledge that trades take time to develop. Step back from the screen, check back at the hourly close.',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Patience in Randomness',
        detailedFeedback: {
          processVerdict: 'SUPERB PATIENCE. You respected the market auction timeline without forcing premature closure.',
          behavioralMechanism: 'Uncertainty intolerance triggers dopamine deficits, making traders close winning positions just to feel a sense of control.',
          probabilisticReality: 'Large institutional position building requires consolidation before expansion. Exiting in chop cuts you out right before the breakout.',
          practicalTakeaway: 'The market will move when order flow aligns, not when your impatience demands it.',
        },
        reflectionFollowUp: 'Why does watching a slow candle produce anxiety? How can setting a scheduled check timer help?',
      },
      {
        id: 'opt-scratch-out',
        label: 'B. Scratch at Breakeven Because It Is "Taking Too Long"',
        actionText: 'Close at 2348.5 (-$20) because you feel uncomfortable not seeing instant momentum.',
        decisionCategory: 'IMPULSIVE_EXIT',
        isPlanAligned: false,
        shortDescription: 'Impatience Scratch Exit',
        detailedFeedback: {
          processVerdict: 'PROCESS DEFECT. You traded your emotional need for certainty rather than the chart setup.',
          behavioralMechanism: 'Action addiction: confusing activity with productivity.',
          probabilisticReality: 'Closing trades for minor scratches bleeds account balance through commissions while forfeiting the 2R ($200) target.',
          practicalTakeaway: 'Give valid trades the spatial and temporal room they require to reach target or stop.',
        },
        reflectionFollowUp: 'If this setup was valid when you clicked buy, what technical factor changed other than the passage of time?',
      },
    ],
  },

  'fear_session_4': {
    id: 'fear_session_4',
    categoryId: 'FEAR',
    title: 'Rule-Based Execution Under Pressure',
    subtitle: 'Overcoming Hesitation at the Setup Trigger Bar',
    symbol: 'USD/JPY',
    timeframe: 'M15',
    tradeDirection: 'SHORT',
    entryPrice: 154.40,
    stopLossPrice: 154.65, // 25 pips ($100)
    takeProfitPrice: 153.90, // 50 pips ($200)
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: ['Hourly close above 154.65 key resistance'],
    learningObjective: 'Overcome execution freeze by verifying that all technical rules are checked and clicking without emotional hesitation.',
    pressureCandleIndex: 3,
    pressureEventTitle: 'A+ CONFLUENCE TRIGGER BAR CLOSES (FEAR OF LOSS FREEZE)',
    pressureEventDescription: 'The M15 bearish engulfing candle closes cleanly at resistance. All 4 checklist rules are green. Yet your finger freezes on the mouse—the thought "What if this is another loss?" paralyzes you.',
    floatingRAtPressure: 0.0,
    candles: [
      { index: 0, time: '08:00', open: 154.10, high: 154.30, low: 154.05, close: 154.28, isUp: true },
      { index: 1, time: '08:15', open: 154.28, high: 154.55, low: 154.25, close: 154.52, isUp: true, annotation: 'Tests Resistance' },
      { index: 2, time: '08:30', open: 154.52, high: 154.60, low: 154.38, close: 154.40, isUp: false, annotation: 'TRIGGER BAR CLOSES' },
      { index: 3, time: '08:45', open: 154.40, high: 154.42, low: 154.15, close: 154.18, isUp: false, annotation: 'RUNNING DOWN (-22 Pips)' },
      { index: 4, time: '09:00', open: 154.18, high: 154.20, low: 153.88, close: 153.90, isUp: false, annotation: 'TARGET HIT (50 Pips)' },
    ],
    options: [
      {
        id: 'opt-execute-decisively',
        label: 'A. Check All 4 Criteria, Accept 1R Risk, Click Execute Instantly',
        actionText: 'Verify trend, resistance, engulfing close, risk size. Click Sell Limit / Market. Do not deliberate.',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Decisive Rule-Based Execution',
        detailedFeedback: {
          processVerdict: 'FLAWLESS EXECUTION DISCIPLINE. You acted as an objective execution clerk.',
          behavioralMechanism: 'Treating execution as a rule audit bypasses outcome bias. You trade the system, not the individual outcome.',
          probabilisticReality: 'Every trading edge is distributed across a large sample size. Skipping valid setups degrades edge expectancy.',
          practicalTakeaway: 'The outcome of this single trade is unknown and irrelevant. What matters is taking the next 50 identical setups flawlessly.',
        },
        reflectionFollowUp: 'What mantra or rule reminder helps you execute without hesitating when your checklist is met?',
      },
      {
        id: 'opt-wait-more-confirmation',
        label: 'B. Wait for "One More Candle" of Confirmation Before Entering',
        actionText: 'Hesitate because of fear. Wait until price has already fallen 25 pips before chasing.',
        decisionCategory: 'HESITATION',
        isPlanAligned: false,
        shortDescription: 'Hesitation & Late Chase',
        detailedFeedback: {
          processVerdict: 'SYSTEM DEGRADATION. By waiting for "extra safety", you entered 22 pips worse with 2x risk.',
          behavioralMechanism: 'The illusion of safety: feeling more confident only after price has already moved, worsening risk-reward.',
          probabilisticReality: 'Entering late destroys the math of your edge. You take larger losses and smaller rewards.',
          practicalTakeaway: 'When the technical trigger appears, execute immediately or let the trade go. Never chase a late move.',
        },
        reflectionFollowUp: 'How does waiting for extra confirmation actually increase your trading risk instead of decreasing it?',
      },
    ],
  },

  'fear_session_5': {
    id: 'fear_session_5',
    categoryId: 'FEAR',
    title: 'Post-Event Reflection and Recovery Planning',
    subtitle: 'Absorbing a Clean 1R Stop-Out with Composure',
    symbol: 'NAS100',
    timeframe: 'M5',
    tradeDirection: 'LONG',
    entryPrice: 19800,
    stopLossPrice: 19760, // 40 pts = 1R ($100)
    takeProfitPrice: 19920,
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: ['M5 close below 19760 demand zone'],
    learningObjective: 'Accept an objective stop-out with zero self-blame and avoid the toxic urge to immediately revenge trade.',
    pressureCandleIndex: 4,
    pressureEventTitle: 'STOP-LOSS TRIGGERED AT 19760 (−1.0R CLEAN LOSS)',
    pressureEventDescription: 'The market sweeps through 19760 and fills your stop loss cleanly. Your account registers -$100. A wave of irritation and the impulse to immediately flip short or double buy surges.',
    floatingRAtPressure: -1.0,
    candles: [
      { index: 0, time: '15:30', open: 19780, high: 19810, low: 19775, close: 19805, isUp: true },
      { index: 1, time: '15:35', open: 19805, high: 19815, low: 19795, close: 19800, isUp: false, annotation: 'LONG ENTRY 19800' },
      { index: 2, time: '15:40', open: 19800, high: 19805, low: 19770, close: 19775, isUp: false },
      { index: 3, time: '15:45', open: 19775, high: 19780, low: 19758, close: 19760, isUp: false, annotation: 'STOPPED OUT (-1.0R)' },
      { index: 4, time: '15:50', open: 19760, high: 19765, low: 19740, close: 19745, isUp: false, annotation: 'POST-LOSS POINT' },
      { index: 5, time: '15:55', open: 19745, high: 19760, low: 19735, close: 19755, isUp: true },
    ],
    options: [
      {
        id: 'opt-accept-loss-log',
        label: 'A. Acknowledge Wholesale Cost of Business, Log in Journal, Step Away',
        actionText: 'Stand up, log the trade as a plan-compliant 1R loss, take a 15-minute physical walk.',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Professional Risk Absorption',
        detailedFeedback: {
          processVerdict: 'PERFECT PROFESSIONAL CONDUCT. You accepted the loss without emotional debt.',
          behavioralMechanism: 'Decoupling trading losses from self-worth transforms a stop-out into simple inventory cost.',
          probabilisticReality: 'A stop loss is your insurance policy. It worked perfectly by limiting account impact to exactly 1.0%.',
          practicalTakeaway: 'You kept risk small and followed rules. Your trading capital and emotional capital remain 100% intact.',
        },
        reflectionFollowUp: 'What phrase can you say to yourself after a loss that immediately grounds your mindset?',
      },
      {
        id: 'opt-revenge-reverse',
        label: 'B. Immediately Reverse to Short with 2x Size to Recover the $100',
        actionText: 'Click Market Sell with 2 lots to ride the downward momentum and get your money back right now.',
        decisionCategory: 'RISK_ESCALATION',
        isPlanAligned: false,
        shortDescription: 'Revenge Spiral Trigger',
        detailedFeedback: {
          processVerdict: 'CRITICAL EMOTIONAL TILT. This is the primary behavioral pattern that causes blown accounts.',
          behavioralMechanism: 'Revenge trading is fueled by wounded pride and dopamine craving, completely blinding you to technical structure.',
          probabilisticReality: 'Trading without a prepared setup right after a loss has a win rate of under 25% and massive drawdown risk.',
          practicalTakeaway: 'Never enter a trade within 10 minutes of a stop-out without walking through your complete checklist.',
        },
        reflectionFollowUp: 'Why did the market taking $100 feel like a personal attack? What does that reveal about your current emotional attachment to money?',
      },
    ],
  },

  // =========================================================================
  // GREED
  // =========================================================================
  'greed_session_1': {
    id: 'greed_session_1',
    categoryId: 'GREED',
    title: 'Profit-Taking & Target Adherence',
    subtitle: 'Locking In +2.5R at Structural Resistance vs Greed Distortion',
    symbol: 'XAU/USD',
    timeframe: 'M15',
    tradeDirection: 'LONG',
    entryPrice: 2360.0,
    stopLossPrice: 2352.0,
    takeProfitPrice: 2380.0, // +2.5R ($250)
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: ['Major daily resistance level reached at 2380'],
    learningObjective: 'Resist the impulse to remove take-profit orders out of euphoria when price expands rapidly.',
    pressureCandleIndex: 4,
    pressureEventTitle: 'TARGET ZONE REACHED (+2.5R / +$250 FLOATING)',
    pressureEventDescription: 'Gold hits your planned target of 2380.0. The candle looks strong, and a greedy inner voice screams: "Delete the take profit! This is going to 2400! Make $1,000!"',
    floatingRAtPressure: 2.5,
    candles: [
      { index: 0, time: '09:00', open: 2360.0, high: 2364.0, low: 2359.5, close: 2363.5, isUp: true },
      { index: 1, time: '09:15', open: 2363.5, high: 2369.0, low: 2362.0, close: 2368.0, isUp: true },
      { index: 2, time: '09:30', open: 2368.0, high: 2374.5, low: 2367.0, close: 2374.0, isUp: true },
      { index: 3, time: '09:45', open: 2374.0, high: 2380.5, low: 2373.0, close: 2380.0, isUp: true, annotation: 'TARGET REACHED (+2.5R)' },
      { index: 4, time: '10:00', open: 2380.0, high: 2381.5, low: 2372.0, close: 2373.5, isUp: false, annotation: 'REVERSAL PINBAR' },
      { index: 5, time: '10:15', open: 2373.5, high: 2374.0, low: 2365.0, close: 2366.0, isUp: false, annotation: 'Gains Erased' },
    ],
    options: [
      {
        id: 'opt-take-profit',
        label: 'A. Honor Planned Take Profit & Bank +2.5R ($250)',
        actionText: 'Execute planned exit or let take-profit limit order fill. Celebrate adherence to the original playbook.',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Plan-Adherent Harvest',
        detailedFeedback: {
          processVerdict: 'OUTSTANDING EXECUTION. You secured asymmetric profits at your predefined objective.',
          behavioralMechanism: 'Greed attempts to renegotiate the trade plan while under the influence of dopamine.',
          probabilisticReality: 'Markets reverse swiftly at key liquidity pools. Refusing to take profit turns 2.5R winners into breakeven or losing trades.',
          practicalTakeaway: 'Professional traders get rich by repeatedly banking high-probability R-multiples, not by hoping for lottery miracles.',
        },
        reflectionFollowUp: 'What helped you resist the temptation to gamble away your locked-in profit?',
      },
      {
        id: 'opt-remove-tp',
        label: 'B. Remove Take Profit and Let It Run Unchecked',
        actionText: 'Delete the 2380 target and hold indefinitely for a fantasy home run.',
        decisionCategory: 'IMPULSE_CHASE',
        isPlanAligned: false,
        shortDescription: 'Greed-Driven Exposure Expansion',
        detailedFeedback: {
          processVerdict: 'GREED PITFALL. The reversal pinbar wiped out over $140 of your gains within 15 minutes.',
          behavioralMechanism: 'Greed blinds traders to impending structural exhaustion.',
          probabilisticReality: 'Unplanned target moves consistently reduce long-term mathematical expectancy.',
          practicalTakeaway: 'Always exit at predefined targets unless your systematic rules specify trailing protocols.',
        },
        reflectionFollowUp: 'How did watching the +$250 profit evaporate down to +$60 feel compared to taking the clean planned exit?',
      },
    ],
  },

  // =========================================================================
  // REVENGE TRADING
  // =========================================================================
  'revenge_session_1': {
    id: 'revenge_session_1',
    categoryId: 'REVENGE_TRADING',
    title: 'Loss Recovery Impulse Simulation',
    subtitle: 'Halting the Revenge Reflex After Consecutive Stop-Outs',
    symbol: 'GBP/JPY',
    timeframe: 'M5',
    tradeDirection: 'SHORT',
    entryPrice: 195.50,
    stopLossPrice: 195.80,
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: ['Two consecutive stop-outs reached in daily session'],
    learningObjective: 'Break the acute emotional urge to immediately re-enter and recover losses from the market.',
    pressureCandleIndex: 3,
    pressureEventTitle: 'SECOND LOSS OF THE MORNING (DAILY LIMIT REACHED)',
    pressureEventDescription: 'Your GBP/JPY short stopped out for -$100. Combined with an earlier loss, you are down -$200 for the day. An overwhelming rage and urgency to make the money back grips you.',
    floatingRAtPressure: -1.0,
    candles: [
      { index: 0, time: '11:00', open: 195.40, high: 195.60, low: 195.35, close: 195.55, isUp: true },
      { index: 1, time: '11:05', open: 195.55, high: 195.65, low: 195.45, close: 195.50, isUp: false, annotation: 'SHORT ENTRY' },
      { index: 2, time: '11:10', open: 195.50, high: 195.82, low: 195.48, close: 195.81, isUp: true, annotation: 'STOPPED OUT (-1R)' },
      { index: 3, time: '11:15', open: 195.81, high: 195.85, low: 195.60, close: 195.65, isUp: false, annotation: 'TILT MOMENT' },
      { index: 4, time: '11:20', open: 195.65, high: 196.20, low: 195.60, close: 196.15, isUp: true, annotation: 'Violent Chop Spike' },
    ],
    options: [
      {
        id: 'opt-enforce-daily-limit',
        label: 'A. Shut Down Platform, Accept Daily Max Loss, Step Away for the Day',
        actionText: 'Honor your risk contract: 2 losses = done for the session. Preserve the remaining 98% of your account.',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Circuit Breaker Activation',
        detailedFeedback: {
          processVerdict: 'SUPERHUMAN DISCIPLINE. You activated the ultimate trader survival tool: the daily stop limit.',
          behavioralMechanism: 'Rage shunts neurological control away from reasoning to raw fight-or-flight aggression.',
          probabilisticReality: 'Traders lose 70%+ of their accounts during revenge trading spirals following normal small losses.',
          practicalTakeaway: 'The market is not your enemy; it has no memory of you. Come back tomorrow with fresh eyes.',
        },
        reflectionFollowUp: 'What physical activity (gym, walk, shower) can you immediately engage in to discharge residual frustration?',
      },
      {
        id: 'opt-double-size-chase',
        label: 'B. Double the Lot Size and Buy the Spike to Get Even',
        actionText: 'Immediately enter Long with 4 lots to wipe out the -$200 loss in one quick green candle.',
        decisionCategory: 'RISK_ESCALATION',
        isPlanAligned: false,
        shortDescription: 'Destructive Tilt Spiral',
        detailedFeedback: {
          processVerdict: 'CATASTROPHIC ERROR. You broke your daily loss limit and doubled position sizing on impulse.',
          behavioralMechanism: 'Ego preservation: refusing to accept that you had an unfavorable probability day.',
          probabilisticReality: 'The subsequent candle chopped violently, causing an additional -$400 drawdown in minutes.',
          practicalTakeaway: 'The quickest way to blow up an account is trying to make back a loss in the next 10 minutes.',
        },
        reflectionFollowUp: 'What would happen to your career if you surrendered to revenge trading every losing day?',
      },
    ],
  },

  // =========================================================================
  // FOMO
  // =========================================================================
  'fomo_session_1': {
    id: 'fomo_session_1',
    categoryId: 'FOMO',
    title: 'Missed-Entry Decision Challenge',
    subtitle: 'Letting a Parabolic Breakout Run Without Chasing',
    symbol: 'EUR/JPY',
    timeframe: 'M5',
    tradeDirection: 'LONG',
    entryPrice: 162.00,
    stopLossPrice: 161.75,
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: ['Valid planned entry price was 162.00; current market price is 162.45 (+45 pips away)'],
    learningObjective: 'Recognize that missed trades cost zero dollars, while chasing parabolic moves creates massive risk.',
    pressureCandleIndex: 2,
    pressureEventTitle: 'MISSED BREAKOUT ROCKETS 45 PIPS (FOMO IMPULSE)',
    pressureEventDescription: 'While fetching coffee, EUR/JPY exploded through resistance. It is up 45 pips without you. You feel sick seeing the green candle expand and your cursor twitches over Market Buy.',
    floatingRAtPressure: 0.0,
    candles: [
      { index: 0, time: '07:45', open: 161.95, high: 162.05, low: 161.90, close: 162.00, isUp: true, annotation: 'PLANNED ENTRY MISSED' },
      { index: 1, time: '07:50', open: 162.00, high: 162.30, low: 161.98, close: 162.28, isUp: true, annotation: 'Explosion +28 Pips' },
      { index: 2, time: '07:55', open: 162.28, high: 162.48, low: 162.25, close: 162.45, isUp: true, annotation: 'PEAK EXPANSION (FOMO)' },
      { index: 3, time: '08:00', open: 162.45, high: 162.46, low: 162.05, close: 162.10, isUp: false, annotation: 'Violent Pullback (-35 Pips)' },
      { index: 4, time: '08:05', open: 162.10, high: 162.15, low: 161.85, close: 161.90, isUp: false, annotation: 'Stop Run Collapse' },
    ],
    options: [
      {
        id: 'opt-let-go',
        label: 'A. Acknowledge Trade Was Missed, Do Not Chase, Wait for Next Setup',
        actionText: 'Repeat rule: "A missed trade costs $0.00. Chasing a 45-pip extended move has horrible risk-reward."',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Abundance Mindset',
        detailedFeedback: {
          processVerdict: 'MASTERFUL RESTRAINT. You avoided buying the literal high of an exhausted liquidity move.',
          behavioralMechanism: 'FOMO creates a false scarcity bias, convincing you that this is the last profitable trade of your life.',
          probabilisticReality: 'The market immediately pulled back 35 pips. Chasing would have trapped you at the absolute top.',
          practicalTakeaway: 'The market generates hundreds of high-probability setups every single week. Never chase.',
        },
        reflectionFollowUp: 'How does realizing that missed trades preserve 100% of your capital change your perspective on FOMO?',
      },
      {
        id: 'opt-market-buy-top',
        label: 'B. Click Market Buy Immediately Because "It is Going to Keep Flying"',
        actionText: 'Enter Long at 162.45 with a stop loss 45 pips away to ride the momentum.',
        decisionCategory: 'IMPULSE_CHASE',
        isPlanAligned: false,
        shortDescription: 'Late FOMO Trap',
        detailedFeedback: {
          processVerdict: 'CLASSIC RETAIL TRAP. You bought liquidity for smart money to exit their positions into.',
          behavioralMechanism: 'Social proof and greed distortion: buying at maximum enthusiasm right before the exhaustion pullback.',
          probabilisticReality: 'Price dumped 55 pips right after your fill, handing you an immediate severe drawdown.',
          practicalTakeaway: 'If you miss an entry, the trade is dead. Await the next valid confluence setup.',
        },
        reflectionFollowUp: 'Why did feeling left out feel worse than following your trading plan?',
      },
    ],
  },

  // =========================================================================
  // HESITATION
  // =========================================================================
  'hesitation_session_1': {
    id: 'hesitation_session_1',
    categoryId: 'HESITATION',
    title: 'Valid Setup Execution Practice',
    subtitle: 'Overcoming Paralysis at the Confluence Trigger',
    symbol: 'USD/CAD',
    timeframe: 'M15',
    tradeDirection: 'SHORT',
    entryPrice: 1.3620,
    stopLossPrice: 1.3645,
    takeProfitPrice: 1.3560,
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: ['M15 close above key resistance at 1.3645'],
    learningObjective: 'Train decisive clicking habits when all systematic parameters are satisfied.',
    pressureCandleIndex: 2,
    pressureEventTitle: 'SETUP MEETS 100% OF SYSTEM CRITERIA (EXECUTION BLOCK)',
    pressureEventDescription: 'Price rejected the daily supply zone with an M15 pinbar. Spread is tight. Your risk is calculated. Yet you stare at the screen for 2 minutes without pulling the trigger.',
    floatingRAtPressure: 0.0,
    candles: [
      { index: 0, time: '13:00', open: 1.3600, high: 1.3625, low: 1.3595, close: 1.3622, isUp: true },
      { index: 1, time: '13:15', open: 1.3622, high: 1.3638, low: 1.3618, close: 1.3620, isUp: false, annotation: 'M15 PINBAR REJECTION' },
      { index: 2, time: '13:30', open: 1.3620, high: 1.3622, low: 1.3610, close: 1.3612, isUp: false, annotation: 'TRIGGER WINDOW' },
      { index: 3, time: '13:45', open: 1.3612, high: 1.3614, low: 1.3585, close: 1.3588, isUp: false, annotation: 'Expansion Down' },
      { index: 4, time: '14:00', open: 1.3588, high: 1.3590, low: 1.3560, close: 1.3560, isUp: false, annotation: 'TARGET HIT (+2.4R)' },
    ],
    options: [
      {
        id: 'opt-pull-trigger',
        label: 'A. Execute Order According to Rule Criteria Without Second-Guessing',
        actionText: 'Acknowledge the fear, check the criteria, and click Sell Limit / Market immediately.',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Decisive Rule Adherence',
        detailedFeedback: {
          processVerdict: 'EXCELLENT CONVICTION. You acted as a disciplined risk manager.',
          behavioralMechanism: 'Hesitation is fear of being wrong disguised as "caution".',
          probabilisticReality: 'Hesitating degrades your edge. You either enter late at a worse price or miss the move entirely.',
          practicalTakeaway: 'The secret to eliminating hesitation is accepting the stop-loss risk completely before looking for the setup.',
        },
        reflectionFollowUp: 'What was the specific catastrophic thought holding your finger back?',
      },
      {
        id: 'opt-freeze-and-miss',
        label: 'B. Keep Analyzing and Staring Until Price Has Already Fallen 30 Pips',
        actionText: 'Deliberate, check 3 other timeframes, look for confirmation on Twitter, and miss the trade.',
        decisionCategory: 'HESITATION',
        isPlanAligned: false,
        shortDescription: 'Analysis Paralysis Freeze',
        detailedFeedback: {
          processVerdict: 'SYSTEM FAILURE THROUGH INACTION. You allowed ungrounded fear to steal your profitable edge.',
          behavioralMechanism: 'Perfectionism and outcome terror paralyzing your motor execution.',
          probabilisticReality: 'Watching a trade you analyzed reach 2.4R without you causes more psychological damage than a planned 1R loss.',
          practicalTakeaway: 'Build a binary checklist: if 4 of 4 boxes are checked, execution is mandatory.',
        },
        reflectionFollowUp: 'How does hesitating on valid setups create regret that leads to revenge trading later?',
      },
    ],
  },
};

// Fallback generator for other categories so every single category has a rich, tailored scenario
export function getScenarioForCategory(categoryId: string, sessionId?: string): TradingScenario {
  // If specific session scenario exists, return it
  if (sessionId && SCENARIOS_DATABASE[sessionId]) {
    return SCENARIOS_DATABASE[sessionId];
  }

  // Check if category has a primary scenario
  const directMatchKey = `${categoryId.toLowerCase()}_session_1`;
  if (SCENARIOS_DATABASE[directMatchKey]) {
    return SCENARIOS_DATABASE[directMatchKey];
  }

  // Fallback tailored scenario for remaining categories
  return {
    id: `scenario-${categoryId.toLowerCase()}`,
    categoryId: categoryId,
    title: `${categoryId.replace(/_/g, ' ')} Behavioral Challenge`,
    subtitle: 'Real-Time Market Pressure & Systematic Rule Compliance',
    symbol: 'EUR/USD',
    timeframe: 'M15',
    tradeDirection: 'LONG',
    entryPrice: 1.0850,
    stopLossPrice: 1.0825,
    takeProfitPrice: 1.0910,
    riskR: 1.0,
    accountBalance: 10000,
    plannedDollarRisk: 100,
    invalidationCriteria: [
      'Candle close beyond structural invalidation mark (1.0825)',
      'Violation of predefined daily risk boundary',
    ],
    learningObjective: `Practice recognizing ${categoryId.replace(/_/g, ' ')} triggers and adhering strictly to predefined risk limits.`,
    pressureCandleIndex: 3,
    pressureEventTitle: `CRITICAL BEHAVIORAL INFLECTION (${categoryId.replace(/_/g, ' ')})`,
    pressureEventDescription: `A simulated market movement tests your emotional boundaries regarding ${categoryId.replace(/_/g, ' ')}. Your predefined plan provides clear criteria, but internal emotional pressure urges an impulsive deviation.`,
    floatingRAtPressure: -0.5,
    candles: [
      { index: 0, time: '10:00', open: 1.0835, high: 1.0848, low: 1.0832, close: 1.0846, isUp: true },
      { index: 1, time: '10:15', open: 1.0846, high: 1.0858, low: 1.0844, close: 1.0852, isUp: true, annotation: 'VALID ENTRY' },
      { index: 2, time: '10:30', open: 1.0852, high: 1.0855, low: 1.0838, close: 1.0840, isUp: false },
      { index: 3, time: '10:45', open: 1.0840, high: 1.0842, low: 1.0832, close: 1.0835, isUp: false, annotation: 'STRESS TEST (-0.5R)' },
      { index: 4, time: '11:00', open: 1.0835, high: 1.0858, low: 1.0834, close: 1.0855, isUp: true, annotation: 'Structure Hold' },
      { index: 5, time: '11:15', open: 1.0855, high: 1.0875, low: 1.0850, close: 1.0870, isUp: true, annotation: 'Expansion +0.8R' },
    ],
    options: [
      {
        id: 'opt-plan-aligned',
        label: 'A. Follow Predefined Trading Plan & Validate Invalidation Criteria',
        actionText: 'Verify that invalidation has not been triggered. Maintain technical stop and let probability unfold.',
        decisionCategory: 'PLAN_ALIGNED',
        isPlanAligned: true,
        shortDescription: 'Systematic Process Adherence',
        detailedFeedback: {
          processVerdict: 'OUTSTANDING DISCIPLINE. You followed your rules despite emotional pressure.',
          behavioralMechanism: 'Separating emotional sensation from operational behavior is the hallmark of elite trading performance.',
          probabilisticReality: 'Edges only manifest over a long horizon of consistent, disciplined rule adherence.',
          practicalTakeaway: 'Always prioritize process fidelity over the outcome of any individual trade.',
        },
        reflectionFollowUp: 'What physical cue reminded you to pause and evaluate the plan instead of reacting impulsively?',
      },
      {
        id: 'opt-emotional-deviation',
        label: `B. Deviate from Plan Due to ${categoryId.replace(/_/g, ' ')} Impulse`,
        actionText: `Surrender to the immediate impulse driven by ${categoryId.replace(/_/g, ' ')} and modify the trade without technical validation.`,
        decisionCategory: 'IMPULSIVE_EXIT',
        isPlanAligned: false,
        shortDescription: 'Emotional Rule Breach',
        detailedFeedback: {
          processVerdict: 'PROCESS VIOLATION. Emotional reaction superseded pre-committed rules.',
          behavioralMechanism: `The cognitive trap of ${categoryId.replace(/_/g, ' ')} bypassed rational prefrontal cortex governance.`,
          probabilisticReality: 'Deviating from your plan introduces uncalculated randomness into your trading business.',
          practicalTakeaway: 'Notice the sensation of the urge, breathe, and commit to honoring the trade plan.',
        },
        reflectionFollowUp: 'What was the immediate emotional belief that convinced you to break your rule?',
      },
    ],
  };
}
