export interface EconomicEvent {
  id: string;
  date: string; // YYYY-MM-DD
  timePkt: string; // e.g., "05:30 PM" (Pakistan Standard Time)
  country: string; // "USD"
  currency: string;
  eventName: string;
  importance: 'HIGH' | 'MEDIUM' | 'LOW';
  actual?: string;
  forecast: string;
  previous: string;
  status: 'UPCOMING' | 'RELEASED' | 'REVISED';
  source: string;
  description: string;
  whyItMatters: string;
  affectedCurrencies: string[];
  higherExpectedImplication: string;
  lowerExpectedImplication: string;
  assetImpacts: {
    usd: string;
    gold: string; // XAUUSD
    forex: string; // EURUSD, GBPUSD
    treasuryYields: string;
    riskSentiment: string; // US30, NAS100
  };
  historicalInsight: string;
}

export const US_ECONOMIC_EVENTS: EconomicEvent[] = [
  {
    id: 'cpi-sep-2026',
    date: '2026-09-11',
    timePkt: '05:30 PM',
    country: 'United States',
    currency: 'USD',
    eventName: 'Core Consumer Price Index (Core CPI) MoM',
    importance: 'HIGH',
    actual: '0.3%',
    forecast: '0.2%',
    previous: '0.2%',
    status: 'RELEASED',
    source: 'U.S. Bureau of Labor Statistics',
    description: 'Measures the change in the price of goods and services purchased by consumers, excluding volatile food and energy costs.',
    whyItMatters: 'Core CPI is the Federal Reserve\'s preferred measure of underlying inflation pressures. Persistent high readings force the Fed to maintain or hike policy interest rates.',
    affectedCurrencies: ['USD', 'EUR', 'GBP', 'JPY'],
    higherExpectedImplication: 'Hawkish for Fed policy. Suggests persistent inflation, reducing probabilities of imminent rate cuts.',
    lowerExpectedImplication: 'Dovish for Fed policy. Signals cooling inflation, opening the door for policy easing and rate cuts.',
    assetImpacts: {
      usd: 'Higher Core CPI typically drives USD rallies against majors as yield expectations surge.',
      gold: 'Bearish for Gold due to higher real interest rates and dollar strength; bullish if CPI misses lower.',
      forex: 'EURUSD and GBPUSD drop under upside USD momentum.',
      treasuryYields: '10-year and 2-year Treasury yields spike higher on upside surprises.',
      riskSentiment: 'Equities (US30, NAS100) often drop initially on higher rate discount fears.',
    },
    historicalInsight: 'Historically, intraday volatility on Core CPI releases exceeds 80 pips on EURUSD and $25 on Gold within the first 15 minutes of release.',
  },
  {
    id: 'ppi-sep-2026',
    date: '2026-09-12',
    timePkt: '05:30 PM',
    country: 'United States',
    currency: 'USD',
    eventName: 'Producer Price Index (PPI) MoM',
    importance: 'HIGH',
    forecast: '0.2%',
    previous: '0.1%',
    status: 'UPCOMING',
    source: 'U.S. Bureau of Labor Statistics',
    description: 'Measures the average change over time in selling prices received by domestic producers for their output (wholesale inflation).',
    whyItMatters: 'PPI acts as a leading indicator of consumer price inflation. When producers pay more for raw inputs, they eventually pass these costs to retail consumers.',
    affectedCurrencies: ['USD', 'XAU'],
    higherExpectedImplication: 'Indicates rising wholesale pipeline pressures that feed into future CPI and PCE numbers.',
    lowerExpectedImplication: 'Indicates wholesale margin deflation, relieving consumer price pressures.',
    assetImpacts: {
      usd: 'Bullish on upside surprises.',
      gold: 'Bearish on hot prints, bullish on softer prints.',
      forex: 'Negative for EURUSD, GBPUSD on USD strength.',
      treasuryYields: 'Treasury yields move higher on higher wholesale price growth.',
      riskSentiment: 'Mixed; depends on whether markets fear rate hikes or celebrate economic robustness.',
    },
    historicalInsight: 'PPI often confirms or contradicts the previous day\'s CPI print, triggering second-wave weekly positioning.',
  },
  {
    id: 'fomc-rate-sep-2026',
    date: '2026-09-16',
    timePkt: '11:00 PM',
    country: 'United States',
    currency: 'USD',
    eventName: 'Fed Interest Rate Decision & Statement',
    importance: 'HIGH',
    forecast: '5.00%',
    previous: '5.25%',
    status: 'UPCOMING',
    source: 'Federal Reserve Open Market Committee (FOMC)',
    description: 'The benchmark target range for the federal funds rate set by the FOMC, determining the cost of overnight borrowing between banks.',
    whyItMatters: 'This is the most critical monetary policy event in global finance. It directly alters global liquidity, currency valuations, and lending rates.',
    affectedCurrencies: ['USD', 'ALL'],
    higherExpectedImplication: 'Hawkish policy hold or hike drives massive global dollar strength.',
    lowerExpectedImplication: 'Dovish rate cut weakens USD, causing massive risk-on rallies in equities and metals.',
    assetImpacts: {
      usd: 'Strengthens on hawkish guidance; weakens on aggressive rate cuts.',
      gold: 'Rallies aggressively on rate cuts or dovish guidance; sells off on prolonged high rates.',
      forex: 'Sharp volatile trends across all major and cross pairs.',
      treasuryYields: 'Short-term yields (2Y) adjust immediately to the revised terminal rate trajectory.',
      riskSentiment: 'Equities surge on cuts; experience liquidity contraction on hawkish holds.',
    },
    historicalInsight: 'Spreads widen dramatically during FOMC statements. Tactical traders must avoid market orders during the initial 5 minutes.',
  },
  {
    id: 'fomc-press-sep-2026',
    date: '2026-09-16',
    timePkt: '11:30 PM',
    country: 'United States',
    currency: 'USD',
    eventName: 'FOMC Press Conference (Fed Chair Jerome Powell)',
    importance: 'HIGH',
    forecast: '-',
    previous: '-',
    status: 'UPCOMING',
    source: 'Federal Reserve Board of Governors',
    description: 'Fed Chair provides 60 minutes of policy rationale and answers questions regarding future rate projections and economic dual mandates.',
    whyItMatters: 'Words and tone during Q&A frequently reverse the initial market moves seen at 11:00 PM when the formal statement is published.',
    affectedCurrencies: ['USD', 'ALL'],
    higherExpectedImplication: 'Hawkish words ("prepared to tighten further", "higher for longer") spark USD surge.',
    lowerExpectedImplication: 'Dovish remarks ("disinflation is broad-based", "risks to employment") weaken USD.',
    assetImpacts: {
      usd: 'Highly volatile, two-way chop likely during Q&A.',
      gold: 'Wild swings between key daily support and resistance levels.',
      forex: 'Liquidity sweeps across Asian/London session highs and lows.',
      treasuryYields: 'Fluctuates with every sentence regarding future meeting expectations.',
      riskSentiment: 'Rapid intraday reversals on Wall Street indices.',
    },
    historicalInsight: 'The press conference often sees "fakeout" moves in the first 15 minutes that reverse completely by the 45-minute mark.',
  },
  {
    id: 'retail-sales-sep-2026',
    date: '2026-09-17',
    timePkt: '05:30 PM',
    country: 'United States',
    currency: 'USD',
    eventName: 'Retail Sales MoM & Core Retail Sales',
    importance: 'HIGH',
    forecast: '0.4%',
    previous: '0.1%',
    status: 'UPCOMING',
    source: 'U.S. Census Bureau',
    description: 'Measures the total receipts of retail stores. Consumer spending accounts for over two-thirds of U.S. economic activity (GDP).',
    whyItMatters: 'A direct thermometer of American consumer health. Strong spending demonstrates resilience; weak spending suggests contraction.',
    affectedCurrencies: ['USD'],
    higherExpectedImplication: 'Validates economic strength; diminishes immediate recession fears.',
    lowerExpectedImplication: 'Signals consumer fatigue and macroeconomic slowdown.',
    assetImpacts: {
      usd: 'Positive on beats; negative on misses.',
      gold: 'Bearish if spending is robust (higher yields); bullish if consumer spending collapses.',
      forex: 'GBPUSD and EURUSD respond directly to USD momentum.',
      treasuryYields: 'Yields track economic growth prospects.',
      riskSentiment: 'Consumer discretionary stocks rally on strong consumer retail demand.',
    },
    historicalInsight: 'Pay close attention to revisions from the previous month, as they often alter market interpretation.',
  },
  {
    id: 'jobless-claims-weekly',
    date: '2026-09-18',
    timePkt: '05:30 PM',
    country: 'United States',
    currency: 'USD',
    eventName: 'Initial Jobless Claims (Weekly)',
    importance: 'MEDIUM',
    forecast: '228K',
    previous: '232K',
    status: 'UPCOMING',
    source: 'U.S. Department of Labor',
    description: 'Weekly count of individuals who filed for unemployment insurance for the first time.',
    whyItMatters: 'The fastest, most timely high-frequency snapshot of U.S. labor market layoffs.',
    affectedCurrencies: ['USD'],
    higherExpectedImplication: 'Labor market softening; dovish for the Fed.',
    lowerExpectedImplication: 'Labor market remains tight; hawkish for the Fed.',
    assetImpacts: {
      usd: 'Weakens if claims exceed 250K; strengthens if claims drop below 215K.',
      gold: 'Rallies on spikes in unemployment claims.',
      forex: 'Fast 15-30 pip intraday reaction.',
      treasuryYields: 'Yields decline on higher layoffs.',
      riskSentiment: 'Bad news for jobs can be good news for stocks if it accelerates rate cut forecasts.',
    },
    historicalInsight: 'A 4-week moving average above 240K historically marks inflection points toward Federal Reserve rate-cutting cycles.',
  },
  {
    id: 'nfp-oct-2026',
    date: '2026-10-02',
    timePkt: '05:30 PM',
    country: 'United States',
    currency: 'USD',
    eventName: 'Non-Farm Payrolls (NFP) & Unemployment Rate',
    importance: 'HIGH',
    forecast: '175K',
    previous: '162K',
    status: 'UPCOMING',
    source: 'U.S. Bureau of Labor Statistics',
    description: 'Total number of paid workers in the U.S. excluding farm employees, government workers, and private household employees.',
    whyItMatters: 'The undisputed heavyweight monthly economic release. Dictates monetary policy stance on maximum employment.',
    affectedCurrencies: ['USD', 'ALL'],
    higherExpectedImplication: 'Strong job creation supports consumer demand and postpones rate cuts.',
    lowerExpectedImplication: 'Sub-100K print signals rapid cooling and escalates emergency rate cut debates.',
    assetImpacts: {
      usd: 'Surges on upside surprise (+220K); plunges on miss (<120K).',
      gold: 'Experiences extreme directional expansion ($30-$50 moves are typical).',
      forex: 'Massive volatility across EURUSD, GBPUSD, USDJPY.',
      treasuryYields: '2-year yield moves violently based on employment strength.',
      riskSentiment: 'High payrolls + low wage inflation creates the optimal "goldilocks" equity rally.',
    },
    historicalInsight: 'Watch Average Hourly Earnings (wage inflation). A high payroll count paired with falling wages often creates an initial fakeout.',
  },
  {
    id: 'pce-oct-2026',
    date: '2026-10-30',
    timePkt: '05:30 PM',
    country: 'United States',
    currency: 'USD',
    eventName: 'Core PCE Price Index YoY (Fed Target Inflation)',
    importance: 'HIGH',
    forecast: '2.6%',
    previous: '2.7%',
    status: 'UPCOMING',
    source: 'U.S. Bureau of Economic Analysis (BEA)',
    description: 'Personal Consumption Expenditures excluding food and energy. The Federal Reserve\'s official 2.0% statutory inflation benchmark.',
    whyItMatters: 'Because it adjusts for consumer substitution behavior, the FOMC bases its formal summary of economic projections on PCE rather than CPI.',
    affectedCurrencies: ['USD'],
    higherExpectedImplication: 'Prevents the Fed from claiming victory over inflation; delays rate cuts.',
    lowerExpectedImplication: 'Provides green light for rate reductions toward neutral policy.',
    assetImpacts: {
      usd: 'Trends directionally with the deviation from the 2.0% target.',
      gold: 'Direct inverse correlation with PCE real interest rate expectations.',
      forex: 'Substantial medium-term positioning adjustments by macro hedge funds.',
      treasuryYields: 'Direct repricing of long-duration bonds.',
      riskSentiment: 'Lower PCE unlocks prolonged multi-week rallies in tech and growth sectors.',
    },
    historicalInsight: 'PCE confirms the broad trend spotted earlier by CPI, cementing monthly central bank policy projections.',
  },
];
